<?php
    $_product = Mage::registry('product');
	$product_id = Mage::getModel('dailydeal/dailydeal')->getDailyDeal();
	$display_qty = Mage::getStoreConfig('dailydeal/configuration/qty');
?>
<?php if ($product_id==$_product->getId() && Mage::getStoreConfig('dailydeal/configuration/enabled')): ?>		
	<!-- COUNTDOWN -->
	<div class="clear"></div><br/>
	<?php
		$dailydeal = Mage::getModel('dailydeal/dailydeal')->getCollection()->addFieldToFilter('status', array('eq' => 3))->addFieldToFilter('product_id', $_product->getId())->getFirstItem();
		$this->getNrViews();
	?>	
	
	<div class="main-countdown">
		<?php echo $this->getCountdown('284px','75px','product_view',null,$_product->getId()); ?>
	</div>
	<?php if (($_product->getTypeId()=='simple' || $_product->getTypeId()=='virtual' || $_product->getTypeId()=='downloadable') && $display_qty): ?>
		<p style="color:#a71d1d; font-family:Arial; font-size:13px;">Hurry, there are only <b style="color:#000;"><?php echo $dailydeal->getDealQty(); ?> item(s)</b> left!</p> 
	<?php endif; ?>

	<!-- COUNTDOWN END -->
<?php endif; ?>