<?php
  $_product = Mage::registry('product');  		
	if (!isset($_product)) {
		$current_product_id = 0;
	} else {
		$current_product_id = $_product->getId();
	}
		
  $product_id = Mage::getModel('dailydeal/dailydeal')->getDailyDeal();
  if (!is_null($product_id) && $current_product_id!=$product_id && Mage::getStoreConfig('dailydeal/configuration/enabled') && Mage::getStoreConfig('dailydeal/sidebar_configuration/right_sidebar')): 

    $_product = Mage::getModel('catalog/product')->load($product_id);	
	$display_qty = Mage::getStoreConfig('dailydeal/sidebar_configuration/display_qty');
	
	// CURRENCY CONVERSION
	$currency_symbol = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol();
	$baseCurrencyCode = Mage::app()->getStore()->getBaseCurrencyCode();
	$currentCurrencyCode = Mage::app()->getStore()->getCurrentCurrencyCode();		

    $_coreHelper = $this->helper('core');
    $_weeeHelper = $this->helper('weee');
    $_taxHelper  = $this->helper('tax');

    $_simplePricesTax = ($_taxHelper->displayPriceIncludingTax() || $_taxHelper->displayBothPrices());
	
    $dailydeal = Mage::getModel('dailydeal/dailydeal')->getCollection()->addFieldToFilter('status', array('eq' => 3))->addFieldToFilter('product_id', array('eq' => $_product->getId()))->getFirstItem();
	$special_price = $dailydeal->getDealPrice();
		
	if ($special_price!='') {
		$old_price = $_product->getPrice();
		
		$converted_old_price = Mage::helper('directory')->currencyConvert($old_price, $baseCurrencyCode, $currentCurrencyCode);
		$old_price_tax = $_taxHelper->getPrice($_product, $converted_old_price, $_simplePricesTax);
		$converted_special_price = Mage::helper('directory')->currencyConvert($special_price, $baseCurrencyCode, $currentCurrencyCode);
		$special_price_tax = $_taxHelper->getPrice($_product, $converted_special_price, $_simplePricesTax);
	} else {
		$price = $_product->getPrice();
		$converted_price = Mage::helper('directory')->currencyConvert($price, $baseCurrencyCode, $currentCurrencyCode);	
		$price_tax = $_taxHelper->getPrice($_product, $converted_price, $_simplePricesTax);
	}
	
?>	
<div class="block block-countdown">
    <div class="block-title">
        <strong><span><?php echo $this->__('Daily deal') ?></span></strong>
    </div>
    <div class="block-content">
		<?php if (Mage::getStoreConfig('dailydeal/sidebar_configuration/display_name')): ?>
			<a href="<?php echo $this->getUrl('dailydeal'); ?>"><span class="product_name"><?php echo $_product->getName(); ?></span></a><br/>
		<?php endif; ?>
		<div class="container">					
			<?php if ((!Mage::getStoreConfig('dailydeal/sidebar_configuration/display_price') && !$display_qty) || ($_product->getTypeId()=='bundle' || $_product->getTypeId()=='grouped')): ?>
				<a href="<?php echo $this->getUrl('dailydeal'); ?>"><img class="product_image_big" src="<?php echo Mage::helper('catalog/image')->init($_product, 'small_image')->resize(150,150);?>" alt="dailydeal_image" />
			<?php else: ?>
				<a href="<?php echo $this->getUrl('dailydeal'); ?>"><img class="product_image" src="<?php echo Mage::helper('catalog/image')->init($_product, 'small_image')->resize(70,70);?>" alt="dailydeal_image" />
			<?php endif; ?>
			<div class="right-container">
			  <?php if (Mage::getStoreConfig('dailydeal/sidebar_configuration/display_price') && ($_product->getTypeId()=='simple' || $_product->getTypeId()=='virtual' || $_product->getTypeId()=='downloadable' || $_product->getTypeId()=='configurable')): ?>
				<?php if ($special_price!=''): ?>
					<h5 class="old_price"><?php echo $currency_symbol.number_format($old_price_tax,2); ?></h5>  
					<h3><?php echo $currency_symbol.number_format($special_price_tax,2); ?></h3>  
				<?php else: ?>
					<h3><?php echo $currency_symbol.number_format($price_tax,2); ?></h3>   					
				<?php endif; ?>			
			  <?php endif; ?>
			  <?php if ($dailydeal->getId()!='' && ($_product->getTypeId()=='simple' || $_product->getTypeId()=='virtual' || $_product->getTypeId()=='downloadable') && $display_qty): ?>
				<p><b><?php echo $dailydeal->getDealQty(); ?> item(s)</b> left!</p>	
			  <?php endif; ?>
			</div>
			</a>
		</div>
		<div class="countdown">               
			<?php echo $this->getCountdown('170px','45px','sidebar_right',null,$_product->getId()); ?>
        </div>
    </div>    
    <div class="block-footer"></div>
</div>				
<?php endif; ?>